.PHONY: all bios fpga clean benchmark fpga-benchmark

# Default target: Build BIOS and generate FPGA Verilog
all: fpga

# Compile the BIOS
bios:
	$(MAKE) -C bios

# Compile the Benchmark
benchmark:
	$(MAKE) -C benchmarks

# Generate Verilog for FPGA, embedding the BIOS binary
# This runs sbt with the path to the bios.bin generated by the bios target
fpga: bios
	sbt "run bios/bios.bin"

# Generate Verilog for FPGA, embedding the Benchmark binary
fpga-benchmark: benchmark
	sbt "run benchmarks/prime.bin"

# Clean up all artifacts
clean:
	$(MAKE) -C bios clean
	$(MAKE) -C benchmarks clean
	sbt clean
